### ISSUE TITLE
gimme-the-song-fpcalc-linux: command not found

### ISSUE THREAD

**Issue by kausko** [joaodjtr/gimme-the-song#1] opened 2021-04-02 19:38 UTC
Hi @joaodjtr,
I'm getting the error: `gimme-the-song-fpcalc-linux: command not found` on my Vercel deployment (Linux). However, it is working perfectly on my local Windows environment, and my code is completely OS-independent.

Here's the complete error log:
`{"errorType":"Error","errorMessage":"Command failed: gimme-the-song-fpcalc-linux /tmp/Numb.mp3\n/bin/sh: gimme-the-song-fpcalc-linux: command not found\n","code":127,"killed":false,"signal":null,"cmd":"gimme-the-song-fpcalc-linux /tmp/Numb.mp3","stack":["Error: Command failed: gimme-the-song-fpcalc-linux /tmp/Numb.mp3","/bin/sh: gimme-the-song-fpcalc-linux: command not found","","    at ChildProcess.exithandler (child_process.js:308:12)","    at ChildProcess.emit (events.js:315:20)","    at maybeClose (internal/child_process.js:1048:16)","    at Socket.<anonymous> (internal/child_process.js:439:11)","    at Socket.emit (events.js:315:20)","    at Pipe.<anonymous> (net.js:673:12)"]}`

Here's my Next.js source code:
```
import multer from "multer";
import nextConnect from "next-connect";
import { gimme, setGimmeKey } from 'gimme-the-song'
import { unlink } from 'fs'
import { tmpdir } from 'os'

const handler = nextConnect({
  onError: (err, _req, res) => { 
    console.log(err)
    res.status(501).json({ error: err.message })
   },
  onNoMatch: (req, res) => res.status(405).json({ error: req.method + " not allowed"})
})
.use(
  multer({ 
    storage: multer.diskStorage({
      destination: tmpdir(),
      filename: (_req, file, cb) => cb(null, file.originalname.split(' ').join(''))
    })
  })
  .single('audiofile')
)
.post((req, res) => {
  setGimmeKey(process.env.ACOUSTIC_API_KEY)
  gimme(req.file.path, {}, ({ track, trackVariants }) => {
    unlink(req.file.path, err => {
      if (err)
        throw err
      res.status(200).json({
        track,
        trackVariants: trackVariants.filter(variant => !!variant.title && track.title !== variant.title)
      })
    })
  })
})

export default handler

export const config = {
  api: {
    bodyParser: false
  }
}
```

**Comment by joaovct** [comment] 2021-04-03 17:34
Hey @kausko,
I will be looking this. When I tried to deploy my server in Heroku, I also got some problems with Linux because I use Windows too. That's why I also included a binary for Linux. Seems strange that in Vercel servers they are not working.

**Comment by kausko** [comment] 2021-04-03 18:32
> I will be looking this. When I tried to deploy my server in Heroku, I also got some problems with Linux because I use Windows too. That's why I also included a binary for Linux. Seems strange that in Vercel servers they are not working.

Thanks for the swift response @joaodjtr!
I think the Vercel deployment might be failing because it is serverless in nature. So, I tried deploying an Express app on both Azure App Services and Heroku, and noticed an issue.

Postman response on calling fpcalc through a POST request
```
{
    "duration": "186\nFINGERPRINT"
}
```

It seems that on Linux environments the line `stdout.split('\r\n').map(str => str.split('=')[1])` does not behave in the same way as it does on Windows. To test it out, I created a test script using code from `execFPcalc.js` and ran it on both Windows 10 and Ubuntu 20.04 (WSL).

Test script code snippet:
```
const [duration, fingerprint] = stdout.split('\r\n').map(str => str.split('=')[1]);
console.log(duration, fingerprint)
```

Windows O/P ✔️:
```
186 <expected-fingerprint>
```

Ubuntu O/P:
```
186
FINGERPRINT undefined
```

I was able to fix this issue by adding a conditional check: `stdout.split(process.platform === 'win32' ? '\r\n' : '\n')`

If you don't mind, can I create a pull request for this issue?

Also, if you were able to deploy it on Heroku successfully without changes like these, could you send over an example that I can follow?

Thanks!

**Comment by joaovct** [comment] 2021-04-03 19:45
@kausko 
Yeah, of course. Feel free to contribute 😀. 
Testing here, I could reproduce this error in WSL. But I have to investigate deeper why the binary is not installed in Linux environments as is installed in Windows. Maybe npm or yarn needs [sudo](https://stackoverflow.com/questions/40561591/node-package-json-bin-value-command-not-working) for adding new commands (?).
About the Heroku deploy, I have to admit that I didn't anything special besides including the binary for Linux, after that everything has been working.

**Comment by phw** [comment] 2021-04-03 19:52
You should consider calling fpcalc with the --json command line parameter. Then you can parse the entire output as JSON.

**Comment by joaovct** [comment] 2021-04-03 19:59
> You should consider calling fpcalc with the --json command line parameter. Then you can parse the entire output as JSON.

Interesting, I didn't know about this. This implementation still has a lot to improve.

**Comment by joaovct** [comment] 2021-04-03 20:18
@kausko 

Could fix this issue in my local WSL by installing the package globally, following the answers for this [question](https://stackoverflow.com/questions/44060241/npm-package-json-defined-bin-module-command-not-found).

**Comment by kausko** [comment] 2021-04-04 04:46
> Could fix this issue in my local WSL by installing the package globally, following the answers for this [question](https://stackoverflow.com/questions/44060241/npm-package-json-defined-bin-module-command-not-found).

Yes, this approach works @joaodjtr. However, I'm moving on from Vercel (where I originally found this issue) because of its limitations with file handling and multipart formdata.

For the second issue, I'll incorporate @phw's suggestion and create a PR. Parsing JSON produces consistent results on both environments.

**Comment by joaovct** [comment] 2021-04-04 23:38
PR merged and package [updated](https://www.npmjs.com/package/gimme-the-song).

**Closed as completed by joaovct** 2021-04-04 23:38 UTC

**Comment by kausko** [comment] 2021-04-05 06:18
Hello again @joaodjtr!

`fpcalc()` is working perfectly again, but `gimme()` is returning null when the duration is a floating-point number. It works if duration is converted to an integer (using `Math.floor()` or `Math.truncate()`).

Since this is a small problem, I didn't create a separate issue or PR. Can you add this and update the package again?

**Comment by joaovct** [comment] 2021-04-05 12:55
@kausko 

I didn't notice. Sorry about that. Fixed and [updated](https://www.npmjs.com/package/gimme-the-song).
Thanks 👌🏽
